import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");
const sharedSource = resolve(root, "src/shared");

async function walk(base, dir=base, out=[]) {
  for (const name of (await readdir(dir)).sort()) {
    const path=join(dir,name), info=await stat(path);
    if (info.isDirectory()) await walk(base,path,out);
    else out.push(relative(base,path).replaceAll("\\", "/"));
  }
  return out;
}

async function fileHashes(dir) {
  const hashes={};
  for (const rel of await walk(dir)) {
    const bytes=await readFile(join(dir,rel));
    hashes[rel]=createHash("sha256").update(bytes).digest("hex");
  }
  return hashes;
}

function runtimePublicSuffixList(source) {
  const rules = String(source || "")
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line && !line.startsWith("//"));
  const version = String(source || "").match(/^\/\/ VERSION:\s*(.+)$/m)?.[1]?.trim() || "unknown";
  const commit = String(source || "").match(/^\/\/ COMMIT:\s*(.+)$/m)?.[1]?.trim() || "unknown";
  return [
    "// Generated rules-only Public Suffix List for MosaicSync runtime.",
    "// Source Code Form: MPL-2.0 — https://mozilla.org/MPL/2.0/",
    `// Upstream VERSION: ${version}; COMMIT: ${commit}`,
    ...rules,
    ""
  ].join("\n");
}

async function readSourceLocaleCatalogs() {
  const localeDir = resolve(sharedSource, "core/i18n-locales");
  const files = (await readdir(localeDir)).filter(name => name.endsWith(".js")).sort();
  const catalogs = new Map();
  for (const file of files) {
    const moduleUrl = `${pathToFileURL(join(localeDir, file)).href}?mosaicsync-build`;
    const module = await import(moduleUrl);
    const messages = module?.MESSAGES;
    if (!messages || typeof messages !== "object" || Array.isArray(messages)) {
      throw new Error(`Invalid source locale catalog: ${file}`);
    }
    catalogs.set(file, messages);
  }
  const english = catalogs.get("en.js");
  if (!english) throw new Error("English source locale catalog is required.");
  const keys = Object.keys(english);
  for (const [file, catalog] of catalogs) {
    const ownKeys = Object.keys(catalog);
    if (ownKeys.length !== keys.length || keys.some(key => !Object.prototype.hasOwnProperty.call(catalog, key))) {
      throw new Error(`Locale catalog key mismatch: ${file}`);
    }
  }
  return { catalogs, keys };
}

function runtimeLocaleHelper(keys) {
  return [
    "/* Generated by tools/build.mjs from the reviewed source locale catalogs. */",
    "/* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. */",
    `const KEYS=Object.freeze(${JSON.stringify(keys)});`,
    "export function createLocaleCatalog(values){",
    "  if(!Array.isArray(values)||values.length!==KEYS.length) return Object.freeze({});",
    "  const catalog=Object.create(null);",
    "  for(let i=0;i<KEYS.length;i+=1) catalog[KEYS[i]]=values[i];",
    "  return Object.freeze(catalog);",
    "}",
    ""
  ].join("\n");
}

function runtimeLocaleModule(keys, catalog) {
  const values = keys.map(key => catalog[key]);
  return [
    "/* Generated compact runtime catalog from the reviewed MosaicSync source locale. */",
    'import { createLocaleCatalog } from "../i18n-runtime-catalog.js";',
    `export const MESSAGES=createLocaleCatalog(${JSON.stringify(values)});`,
    ""
  ].join("\n");
}

async function optimizeRuntimeData(target, localeData, pslRuntime) {
  await writeFile(join(target, "core/public_suffix_list.dat"), pslRuntime, "utf8");
  await writeFile(join(target, "core/i18n-runtime-catalog.js"), runtimeLocaleHelper(localeData.keys), "utf8");
  for (const [file, catalog] of localeData.catalogs) {
    await writeFile(
      join(target, "core/i18n-locales", file),
      runtimeLocaleModule(localeData.keys, catalog),
      "utf8"
    );
  }
}

const [localeData, pslSource] = await Promise.all([
  readSourceLocaleCatalogs(),
  readFile(resolve(sharedSource, "core/public_suffix_list.dat"), "utf8")
]);
const pslRuntime = runtimePublicSuffixList(pslSource);

await rm(dist, { recursive: true, force: true });
for (const browser of ["firefox", "chrome"]) {
  const target = resolve(dist, browser);
  await mkdir(target, { recursive: true });
  await cp(sharedSource, target, { recursive: true });
  await cp(resolve(root, `src/${browser}`), target, { recursive: true, force: true });
  // Keep the reviewed GitHub source human-readable while generating smaller,
  // deterministic runtime-only representations for bulky data that is parsed
  // lazily. The semantic tests verify complete source → runtime equivalence.
  await optimizeRuntimeData(target, localeData, pslRuntime);
}

const manifests={};
for (const browser of ["firefox","chrome"]) {
  const target=resolve(dist,browser);
  const manifest=JSON.parse(await readFile(join(target,"manifest.json"),"utf8"));
  manifests[browser]={version:manifest.version, files:await fileHashes(target)};
}
await writeFile(resolve(root,"build-manifest.json"), `${JSON.stringify({schemaVersion:1,generatedFrom:"shared source + browser overlays + deterministic runtime data compaction",browsers:manifests},null,2)}\n`);
console.log("Built dist/firefox and dist/chrome with deterministic PSL/locale runtime compaction; wrote SHA-256 build-manifest.json.");
